apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-capstone
  labels:
    app: project-capstone
  namespace: default
spec:
  progressDeadlineSeconds: 4000
  replicas: 3
  selector:
    matchLabels:
      app: project-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: project-capstone
    spec:
      containers:
        - image: loiphamvan/project-capstone:latest
          imagePullPolicy: Always
          name: project-capstone
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"