- name: Copy deployment configuration
  copy:
    src: "deployment.yml"
    dest: $HOME

- name: Apply deployment configuration
  shell: "./bin/kubectl apply -f deployment.yml"
  args:
    chdir: $HOME