---
- name: "Save LoadBalancer DNS name"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
  tasks:
    - name: Get the name of LoadBalancer DNS
      shell: "./bin/kubectl get svc {{ ENVIRONMENT_NAME }}"
      register: loadbalancer_dns
      args:
        chdir: $HOME

    - name: Copy the output to the local file
      copy:
        content: "{{ loadbalancer_dns.stdout }}"
        dest: "loadbalancer_dns.txt"
      delegate_to: localhost